### ISSUE TITLE
webrtc  golang 

### ISSUE THREAD

**Issue by wadelee1986** [eddiexue/webrtcmcu#1]
你好，

我叫李伟，对webrtc mcu很感兴趣；

我之前是做voip sip技术支持的，现在干golang 开发，您是做哪块的 ？

**Comment by eddiexue** [comment]
我们做QQ音视频后台，正在预研webrtc和golang，觉得lincode这类开源项目不够稳定，想自己开发一套。不过我们刚开始切入，对webrtc和golang都不熟悉，只是初期的摸索
